controller:
  kind: DaemonSet
  ingressClass: haproxy-shard-1
  ingressClassResource:
    name: haproxy-shard-1
    controllerValue: haproxy.org/haproxy-shard-1
    enabled: true
    default: false
  watchNamespace: "team-alpha"
  nodeSelector:
    network-index: "0"
  tolerations:
    - key: role
      operator: Equal
      value: network
      effect: NoSchedule
  replicaCount: 1
  service:
    type: ClusterIP
  daemonset:
    useHostPort: true
    hostPorts:
      http: 80
      https: 443
      stat: 1024
